
package com.mycompany.mavenproject1.viwer;

import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


import com.mycompany.mavenproject1.Controle.Medic;
import com.mycompany.mavenproject1.Modelo.MedicFabric;
import com.mycompany.mavenproject1.Modelo.Fabrica;


/**
 *
 * @author Aluno
 */
public class TabelaMedicos extends javax.swing.JFrame {

    /**
     * Creates new form TelaHELP
     */
    public TabelaMedicos() {
        initComponents();
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btMenuTM = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMedTM = new javax.swing.JTable();
        btEditDrTM = new javax.swing.JButton();
        btNovoDrTM = new javax.swing.JButton();
        btExcluirDrTM = new javax.swing.JButton();
        btFecharDrTM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btMenuTM.setText("Menu");
        btMenuTM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuTMActionPerformed(evt);
            }
        });
        getContentPane().add(btMenuTM, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 460, -1, 20));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 14, 107, -1));

        jLabel1.setText("Tabela De Medicos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 890, 20));

        tableMedTM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome Dr", "Especialidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableMedTM);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 860, 370));

        btEditDrTM.setText("Editar");
        btEditDrTM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditDrTMActionPerformed(evt);
            }
        });
        getContentPane().add(btEditDrTM, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, -1, 20));

        btNovoDrTM.setText("New DR");
        btNovoDrTM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoDrTMActionPerformed(evt);
            }
        });
        getContentPane().add(btNovoDrTM, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, -1, 20));

        btExcluirDrTM.setText("Excluir");
        btExcluirDrTM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirDrTMActionPerformed(evt);
            }
        });
        getContentPane().add(btExcluirDrTM, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, -1, 20));

        btFecharDrTM.setText("Fechar");
        getContentPane().add(btFecharDrTM, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 460, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMenuTMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuTMActionPerformed

    }//GEN-LAST:event_btMenuTMActionPerformed

    private void btNovoDrTMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoDrTMActionPerformed
  
    }//GEN-LAST:event_btNovoDrTMActionPerformed

    private void btEditDrTMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditDrTMActionPerformed
   
    }//GEN-LAST:event_btEditDrTMActionPerformed

    private void btExcluirDrTMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirDrTMActionPerformed

    }//GEN-LAST:event_btExcluirDrTMActionPerformed
    
    /**
     * @param args the command line arguments
     */
    
 
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEditDrTM;
    private javax.swing.JButton btExcluirDrTM;
    private javax.swing.JButton btFecharDrTM;
    private javax.swing.JButton btMenuTM;
    private javax.swing.JButton btNovoDrTM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tableMedTM;
    // End of variables declaration//GEN-END:variables
}
