/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1.viwer;

import javax.swing.JOptionPane;
import com.mycompany.mavenproject1.Controle.Medic;
import com.mycompany.mavenproject1.Modelo.MedicFabric;
import com.mycompany.mavenproject1.Modelo.Fabrica;


/**
 *
 * @author Aluno
 */
public class TelaCadstroDR extends javax.swing.JFrame {
    
    private String especialidades; 
    
    /**
     * Creates new form TelaCadstroDR
     */
    public TelaCadstroDR() {
        initComponents();
        
        setValor(new Medic());
        this.especialidades = "";
    }
    
    
    public TelaCadstroDR (Medic valor){
        initComponents();
        
        setValor(valor);
        txtNomeDR.setText(valor.getNomeDr());
        //txtEspecia.setText(valor.getEspecialidade());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNomeDR = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButtonCadasDR = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cbNeuro = new javax.swing.JCheckBox();
        cbCardio = new javax.swing.JCheckBox();
        cbCGeral = new javax.swing.JCheckBox();
        cbDermo = new javax.swing.JCheckBox();
        cbEndor = new javax.swing.JCheckBox();
        cbOftmo = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(851, 487));

        jLabel1.setText("Cadastro de Dr,s");

        jLabel2.setText("Nome do Dr:");

        jLabel3.setText("Especialidade:");

        txtNomeDR.setText("Nome Dr");

        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonCadasDR.setText("Cadastrar");
        jButtonCadasDR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonCadasDRMousePressed(evt);
            }
        });
        jButtonCadasDR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadasDRActionPerformed(evt);
            }
        });

        jButton3.setText("Menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cbNeuro.setText("Neurologista");
        cbNeuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNeuroActionPerformed(evt);
            }
        });

        cbCardio.setText("Cardiologista");
        cbCardio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCardioActionPerformed(evt);
            }
        });

        cbCGeral.setText("Clinico Geral");
        cbCGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCGeralActionPerformed(evt);
            }
        });

        cbDermo.setText("Dermatologista");
        cbDermo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDermoActionPerformed(evt);
            }
        });

        cbEndor.setText("Endocrinologista");
        cbEndor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEndorActionPerformed(evt);
            }
        });

        cbOftmo.setText("Oftalmologista");
        cbOftmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOftmoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(581, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCadasDR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNomeDR, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel3)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbCardio)
                                .addComponent(cbCGeral))
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbOftmo)
                                .addComponent(cbEndor))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbNeuro)
                        .addGap(29, 29, 29)
                        .addComponent(cbDermo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomeDR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNeuro)
                    .addComponent(cbDermo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCardio)
                    .addComponent(cbEndor))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCGeral)
                    .addComponent(cbOftmo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 253, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButtonCadasDR)
                    .addComponent(jButton3))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        TelaPrincipal view = new TelaPrincipal();
        view.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonCadasDRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadasDRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCadasDRActionPerformed

    private void jButtonCadasDRMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCadasDRMousePressed
        Medic obj = getValor();
        obj.setNomeDr(txtNomeDR.getText());
        obj.setEspecialidade(especialidades);
        
        setValor(obj);
        
        Fabrica<Medic> fa = new MedicFabric();
        if (fa.salvar(obj)){
            JOptionPane.showMessageDialog(this, "Medico foi cadastrado com Sucesso!.");
            dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Medico não pode ser salvo","Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonCadasDRMousePressed
    
    
    private void cbNeuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNeuroActionPerformed
        if (this.cbNeuro.isSelected()) { 
        if (!this.especialidades.contains("Neurologista")) {
            this.especialidades += "Neurologista^";
        }
    } else {
        this.especialidades = this.especialidades.replace("Neurologista^", "");
    }   
    }//GEN-LAST:event_cbNeuroActionPerformed

    private void cbCardioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCardioActionPerformed
        if (this.cbCardio.isSelected()) { 
        if (!this.especialidades.contains("Cardiologista")) {
            this.especialidades += "Cardiologista^";
        }
    } else {
        this.especialidades = this.especialidades.replace("Cardiologista^", "");
    }
    }//GEN-LAST:event_cbCardioActionPerformed
        
    private void cbCGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCGeralActionPerformed
        if (this.cbCGeral.isSelected()) { 
        if (!this.especialidades.contains("Clinico Geral")) {
            this.especialidades += "Clinico Geral^";
        }
    } else {
        this.especialidades = this.especialidades.replace("Clinico Geral^", "");
    }
    }//GEN-LAST:event_cbCGeralActionPerformed

    private void cbDermoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDermoActionPerformed
        if (this.cbDermo.isSelected()) { 
        if (!this.especialidades.contains("Dermatologista")) {
            this.especialidades += "Dermatologista^";
        }
    } else {
        this.especialidades = this.especialidades.replace("Dermatologista^", "");
    }
    }//GEN-LAST:event_cbDermoActionPerformed

    private void cbEndorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEndorActionPerformed
        if (this.cbEndor.isSelected()) { 
        if (!this.especialidades.contains("Endocrinologista")) {
            this.especialidades += "Endocrinologista^";
        }
    } else {
        this.especialidades = this.especialidades.replace("Endocrinologista^", "");
    }
    }//GEN-LAST:event_cbEndorActionPerformed

    private void cbOftmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOftmoActionPerformed
        if (this.cbOftmo.isSelected()) { 
        if (!this.especialidades.contains("Oftalmologista")) {
            this.especialidades += "Oftalmologista^";
        }
    } else {
        this.especialidades = this.especialidades.replace("Oftalmologista^", "");
    }
    }//GEN-LAST:event_cbOftmoActionPerformed
    
    
    private Medic valor;
    
    public Medic getValor(){
        return valor;
    }
    
    public void setValor(Medic valor){
        this.valor = valor;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadstroDR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadstroDR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadstroDR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadstroDR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadstroDR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbCGeral;
    private javax.swing.JCheckBox cbCardio;
    private javax.swing.JCheckBox cbDermo;
    private javax.swing.JCheckBox cbEndor;
    private javax.swing.JCheckBox cbNeuro;
    private javax.swing.JCheckBox cbOftmo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonCadasDR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtNomeDR;
    // End of variables declaration//GEN-END:variables
}
