/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1.viwer;


import java.text.SimpleDateFormat;
import java.util.Date;



/**
 *
 * @author Matheus
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
        data(data);
        hora(hora); 
        
    }

    Date dataHoraAtual = new Date();
        String data = new SimpleDateFormat("dd/MM/yyyy").format(dataHoraAtual);
        String hora = new SimpleDateFormat("HH:mm:ss").format(dataHoraAtual); 
    
    public void data(String data){
        txtDiaHoje.setText(data);
    }     
    public void hora(String hora){
        txtHorasHoje.setText(hora);
    }
         
    

        
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bCadstroP = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bMarcarCon = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bRelatorio = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        bHistoricoHoje = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        bHistoricoPacinte = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        bCadasDR = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        bAtestado = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        bTabelaMedic = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtDiaHoje = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        txtHorasHoje = new javax.swing.JFormattedTextField();
        bFechar = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        bAtulizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(851, 487));
        setMinimumSize(new java.awt.Dimension(851, 487));
        setPreferredSize(new java.awt.Dimension(851, 487));
        setSize(new java.awt.Dimension(851, 487));

        jLabel1.setText("Cadastro Paciente");

        bCadstroP.setText("Cadastro Paciente");
        bCadstroP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCadstroPActionPerformed(evt);
            }
        });

        jLabel2.setText("Marcar Consulta");

        bMarcarCon.setText("Marcar Consulta");
        bMarcarCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMarcarConActionPerformed(evt);
            }
        });

        jLabel3.setText("Criador De Relatorios");

        bRelatorio.setText("Relatorios");
        bRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRelatorioActionPerformed(evt);
            }
        });

        jLabel4.setText("Consultas Do Dia");

        bHistoricoHoje.setText("Consultas de Hoje");
        bHistoricoHoje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHistoricoHojeActionPerformed(evt);
            }
        });

        jLabel5.setText("Cadastro Dr,s");

        bHistoricoPacinte.setText("Historico");
        bHistoricoPacinte.setMaximumSize(new java.awt.Dimension(117, 23));
        bHistoricoPacinte.setMinimumSize(new java.awt.Dimension(117, 23));
        bHistoricoPacinte.setPreferredSize(new java.awt.Dimension(117, 23));
        bHistoricoPacinte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHistoricoPacinteActionPerformed(evt);
            }
        });

        jLabel6.setText("Historico Do Paciente");

        bCadasDR.setText("Cadastro Dr,s");
        bCadasDR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCadasDRActionPerformed(evt);
            }
        });

        jLabel7.setText("Atestado");

        bAtestado.setText("Atestado");
        bAtestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtestadoActionPerformed(evt);
            }
        });

        jLabel8.setText("Tabela De Medicos");

        bTabelaMedic.setText("Medicos");
        bTabelaMedic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTabelaMedicActionPerformed(evt);
            }
        });

        jLabel9.setText("Menu");

        jLabel10.setText("Dia  :");

        txtDiaHoje.setEditable(false);
        txtDiaHoje.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        txtDiaHoje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaHojeActionPerformed(evt);
            }
        });

        jLabel11.setText("Horas:");

        txtHorasHoje.setEditable(false);
        txtHorasHoje.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        bFechar.setText("Fechar");
        bFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFecharActionPerformed(evt);
            }
        });

        bAtulizar.setText("Atulizar");
        bAtulizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtulizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(bCadstroP))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(bCadasDR, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bMarcarCon)
                                    .addComponent(bHistoricoPacinte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jLabel2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(bAtestado, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70)
                                        .addComponent(bTabelaMedic, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(bRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(70, 70, 70)
                                                .addComponent(bHistoricoHoje)
                                                .addGap(27, 27, 27))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel4)
                                                .addGap(44, 44, 44))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(120, 120, 120)
                                .addComponent(jLabel8)
                                .addGap(42, 42, 42))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDiaHoje, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHorasHoje, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))))
            .addComponent(jSeparator1)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bAtulizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(txtDiaHoje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtHorasHoje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCadstroP)
                    .addComponent(bMarcarCon)
                    .addComponent(bRelatorio)
                    .addComponent(bHistoricoHoje))
                .addGap(27, 27, 27)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCadasDR)
                    .addComponent(bHistoricoPacinte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAtestado)
                    .addComponent(bTabelaMedic))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bFechar)
                    .addComponent(bAtulizar))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCadstroPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCadstroPActionPerformed
        
        TelaCadstro view = new TelaCadstro();
        view.setVisible(true);
        
    }//GEN-LAST:event_bCadstroPActionPerformed

    private void bMarcarConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMarcarConActionPerformed
        
        TelaMarcarConsulta view = new TelaMarcarConsulta();
        view.setVisible(true);
        
    }//GEN-LAST:event_bMarcarConActionPerformed

    private void bRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRelatorioActionPerformed
        // TODO add your handling code here:
        TelaRelatorio view = new TelaRelatorio();
        view.setVisible(true);
    }//GEN-LAST:event_bRelatorioActionPerformed

    private void bHistoricoHojeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHistoricoHojeActionPerformed
        
        TelaCosnultadeHoje view = new TelaCosnultadeHoje();
        view.setVisible(true);
    }//GEN-LAST:event_bHistoricoHojeActionPerformed

    private void bCadasDRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCadasDRActionPerformed
        
        TelaCadstroDR view = new TelaCadstroDR();
        view.setVisible(true);
    }//GEN-LAST:event_bCadasDRActionPerformed

    private void bAtestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtestadoActionPerformed
       
        TelaDoAtestado view = new TelaDoAtestado();
        view.setVisible(true);
    }//GEN-LAST:event_bAtestadoActionPerformed

    private void bHistoricoPacinteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHistoricoPacinteActionPerformed
        
        TelaHistoricoPaciente view = new TelaHistoricoPaciente();
        view.setVisible(true);
    }//GEN-LAST:event_bHistoricoPacinteActionPerformed

    private void bTabelaMedicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTabelaMedicActionPerformed
        
        TabelaMedicos view = new TabelaMedicos();
        view.setVisible(true);
    }//GEN-LAST:event_bTabelaMedicActionPerformed

    private void txtDiaHojeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaHojeActionPerformed
        
    }//GEN-LAST:event_txtDiaHojeActionPerformed

    private void bAtulizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtulizarActionPerformed
        
      
    }//GEN-LAST:event_bAtulizarActionPerformed

    private void bFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFecharActionPerformed
        dispose();
    }//GEN-LAST:event_bFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAtestado;
    private javax.swing.JButton bAtulizar;
    private javax.swing.JButton bCadasDR;
    private javax.swing.JButton bCadstroP;
    private javax.swing.JToggleButton bFechar;
    private javax.swing.JButton bHistoricoHoje;
    private javax.swing.JButton bHistoricoPacinte;
    private javax.swing.JButton bMarcarCon;
    private javax.swing.JButton bRelatorio;
    private javax.swing.JButton bTabelaMedic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JFormattedTextField txtDiaHoje;
    private javax.swing.JFormattedTextField txtHorasHoje;
    // End of variables declaration//GEN-END:variables
}
